### ISSUE TITLE
AdvancedPortals compatibility

### ISSUE THREAD

**Issue by SpartanPlume** [SpikeHimself/XPortal#22]
When a user logs in the server, all AdvancedPortals portals names are reset, so we can't teleport to them anymore. As a workaround for now, we're using backup portals.

Would it be possible to have a compatibility with this mod as I saw there was something similar done in issue #20 ? 

Also, thanks for the mod, it's awesome.

**Comment by SpikeHimself** [comment]
Hi, thanks for reporting!

Could you send me the `LogOutput.log` from a session where this occurs? I'll see what I can do.

**Comment by SpikeHimself** [comment]
While waiting for your response I had a quick glance at Advanced Portals' [patch code](https://github.com/RandyKnapp/ValheimMods/blob/6d5fcd862588e4f0a23ee27e2076b68470451d97/AdvancedPortals/ConnectPortals_Patch.cs#L28) and I noticed something odd. It seems that Advanced Portals is [adding its own custom portal ZDOs](https://github.com/RandyKnapp/ValheimMods/blob/6d5fcd862588e4f0a23ee27e2076b68470451d97/AdvancedPortals/ConnectPortals_Patch.cs#L39) to any call to GetAllZDOsWithPrefab() by replacing that function with a new version. XPortal relies on this function's vanilla behaviour.

But I think the funny part is that this behaviour was added to Advanced Portals in a commit titled "Compat for AnyPortal".

I'd still like to see your logfile, maybe there is something I can do on XPortal's side to work around this, but from what I've seen here (and I might be judging too quickly as I haven't tested anything), it *looks like* the cause might be on Advanced Portals' side.

**Comment by SpikeHimself** [comment]
I have tested the mods together and I am not experiencing your issue.

This is what I did:
- Run a dedicated server
- Launch my game and join it
- Spawn an "ancient portal" next to an existing "normal" portal.
- Renamed my normal portal to "normal".
- Renamed the "ancient portal" to "ancient"
- Logout
- Log back in
- Observed that both portals are still named

There must be another cause to your issue.

Again, if you could provide your `LogOutput.log` with debug logging enabled, I could look into it.

**Comment by SpartanPlume** [comment]
How do you enable debug logging ?
We are using the docker server to run the dedicated server.

**Comment by SpikeHimself** [comment]
> How do you enable debug logging ?

You have to edit a few lines in `Valheim\BepInEx\config\BepInEx.cfg`.

First, in the section `[Harmony.Logger]` there is a setting titled `LogChannels`. Add `Debug` to it, so that it reads:
    LogChannels = Info, Warn, Error, Debug

Then, under the section `[Logging.Disk]` change the setting for `LogLevels` to `All`.

If you also want to see this info in the console, you may edit the same `LogLevels` setting under `[Logging.Console]` to also say `All`, but it's not required for the output file.

**Comment by SpikeHimself** [comment]
@SpartanPlume Were you able to find anything? Are you still experiencing this problem?

**Comment by SpartanPlume** [comment]
Sorry for the delay, I'm not hosting the server and my friend was lazy. I managed to convince them to do it.
I see this line in the log which seems to correspond to the issue: `[Debug  :XPortal.KnownPortalsManager] [KnownPortalsManager.UpdateFromList] Removing 1 portals`

What I did was join the server (all AdvancedPortals were not named because someone connected before me), name one of the AdvancedPortals portal, disconnect and reconnect.

[valheim_server.log](https://github.com/SpikeHimself/XPortal/files/10853528/valheim_server.log)

**Comment by SpikeHimself** [comment]
> [Info   :   BepInEx] Loading [XPortal 1.2.2]

It seems you're still running an older version of XPortal.

The latest version of XPortal is 1.2.5. Could you update XPortal on all clients and on the server, and see if the problem persists?

If that does not solve the issue, then please:
1. disable all other mods to make sure they aren't causing this issue.
2. provide the `LogOutput.log` from the server **and** from your client

I play with Advanced Portals + XPortal on my main world myself, so in the meantime I'll try to reproduce the scenario you've described, and see if I can find anything (but so far I've not had any issues).

Oh, and just for the record, probably not related to the above, you are running BalrondContainers on your server, but it immediately throws an error when it tries to load, because it cannot find its config file:

> [Error  : Unity Log] DirectoryNotFoundException: Could not find a part of the path '/opt/valheim/plus/BepInEx/config/BalrondContainers/Configs'.

**Comment by SpikeHimself** [comment]
By the way, in the log file you sent there's not trace of Advanced Portals. If you're not running Advanced Portals on the server, but only on your client, then the server will not be able to discover those portals. 

This is confirmed by what is happening according to your logfile, which is:

1: the server knows 15 portals
2: player makes a new ( advanced portals) portal 
3: 16 portals *should* now exist
4: player disconnects
5: player connects again
6: the server knows 15 portals

Can you run the same test with Advanced Portals installed on the server?

**Comment by SpartanPlume** [comment]
`If you're not running Advanced Portals on the server, but only on your client, then the server will not be able to discover those portals.`

Indeed that was the issue, we didn't think to check that. And I think adding a note on your mod or AdvancedPortals mod could be useful for sure.
Thanks a lot for the help!
