### ISSUE TITLE
AdvancedPortals Support - Multiple portal dropdowns/lists per portal type.

### ISSUE THREAD

**Issue by AugusDogus** [SpikeHimself/XPortal#27]
I would love for a config option to be added to add an additional compatibility with [AdvancedPortals](https://github.com/RandyKnapp/ValheimMods/tree/main/AdvancedPortals).

Currently all portals, no matter what type, will show up on the dropdown list. Would it be possible to add a configuration option to restrict the visible portals on the dropdown list to the corresponding type of portal that's being interacted with?

Perhaps by creating multiple KnownPortalsManager(s) per portal type/prefab?

**Comment by SpikeHimself** [comment]
Hi, thanks for your post!

I understand the problem, and I think it might indeed be easier if there was a way of seeing what the type of portal is that you're trying to connect to. However, creating a new dropdown for each portal type introduces a few problems. Some are technical in nature but I'll happily battle those. Another is one I'm not happy to battle: what if someone makes a mod that's similar to Advanced Portals, but instead of 3, they add 12 (or any random amount) new portal types? Then will someone come here and suggest I add 12 dropdowns? I don't think this is the best approach.

Cloning the KnownPortalsManager for each portal type is, again, probably technically possible after overcoming some hurdles (or rather: a full refactoring of how that currently works!), but I don't think this is the right approach either. Portal "type" could simply be a property of existing portals, and then you could make other choices in the code based on that.

I could perhaps give the portals in the dropdown a different highlighted colour (or add a character or some other way of making them stand out), depending on what type of portal they are. That might do the trick.

I'm gonna let this be for a bit and see if my brain comes up with anything.

**Comment by SpikeHimself** [comment]
> I would like it if only certain items can only go through the "Advanced Portal" as long as it's linked to another "Advanced Portal" of the same type.

I understand now and completely agree that this would be a better, or at least a lot fairer, approach. But I think this functionality belongs on the Advanced Portals side. It should check, on the teleport trigger, whether the player is allowed to teleport to the connected portal, and display a message if not. Even without XPortal installed, it would currently allow that, right? The game's vanilla behaviour is just to connect portals of the same tag. I don't think Advanced Portals currently modifies that (but I'm not sure).

Of course it would be nice if XPortal could display the portal type before you select the destination, fully agreed on that (and I'll look into that!), but I don't think blocking the player from teleporting fits in XPortal's scope.

**Comment by SpikeHimself** [comment]
![image](https://user-images.githubusercontent.com/123466188/222958166-935b13fc-3e23-467c-9b5d-d15fd651505c.png)

**Comment by SpikeHimself** [comment]
The changes visible in the screenshots above are included in v1.2.6 of XPortal, which released just a few moments ago.

**Comment by SpikeHimself** [comment]
@AugusDogus Have you had a chance to review these changes? What's your opinion?

**Comment by SpikeHimself** [comment]
Hi @AugusDogus. I have not heard from you in 2 weeks, so I am closing this issue. If you'd like to reopen this issue, go right ahead!

> The problem I am currently seeing is players having the ability to access portals that are not the same type as the portal they are interacting with. I would like it if only certain items can only go through the "Advanced Portal" as long as it's linked to another "Advanced Portal" of the same type.

Once more to sum up: This functionality needs to be added by the creator of Advanced Portals. XPortal has no control how the other mod works.
