### ISSUE TITLE
version 1.2.10 NO dll

### ISSUE THREAD

**Issue by GrimmLiberty** [SpikeHimself/XPortal#41]
Yeah, uninstalled twice to be sure, NO DLL included.

**Comment by SpikeHimself** [comment]
Hi, thanks for your report!

But, what are you reporting? Can you explain what you mean? You didn't provide any information.

The XPortal release .zip file includes XPortal.dll as you can see here:

![image](https://user-images.githubusercontent.com/123466188/230558192-14b41503-cbf1-459a-8fc9-c3ee8b993807.png)

**Comment by GrimmLiberty** [comment]
Ok, on Thunderstore.io when I install the latest version of the mod, there is no dll included. 

see log  and pictures of what I am loading... note in the log x-portal isn't loading? that's because it isn't installing any dll (see pictures) 

[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/11178064/LogOutput.log)
![xportal3](https://user-images.githubusercontent.com/10464257/230591190-a36168fc-b674-41cf-a19b-000530652b96.jpg)
![xportal1](https://user-images.githubusercontent.com/10464257/230591191-f3035a29-89eb-4a7b-b7bb-3649ab783704.jpg)
![xportal2](https://user-images.githubusercontent.com/10464257/230591192-4eece18f-3c40-42bb-85d9-9d8c58617761.jpg)

**Comment by SpikeHimself** [comment]
On your third screenshot you are showing the contents of your download. Can you open the XPortal directory there and show me the contents? That's where the DLL should be.

How did you download XPortal? Did you use the "Install with Mod Manager" button on the Thunderstore page?

Did you get any messages from your anti-virus software perhaps? Maybe it removed the DLL file after you installed it because it (incorrectly) thought it was harmful.

I've not used r2modman myself so I'll install that later and see if it works for me.

**Comment by SpikeHimself** [comment]
I have installed r2modman and used it to download and install XPortal, and it works fine:

![image](https://user-images.githubusercontent.com/123466188/230601899-09c94455-f2c3-4e11-adeb-50367fb233e5.png)

![image](https://user-images.githubusercontent.com/123466188/230602019-6c729a2b-2058-405d-b84c-f117cd3423ff.png)

So we can say with absolute certainty:
1. The problem is not in the XPortal release .zip file
2. The problem is not in the Thunderstore release 
3. The problem is not in r2modman

**Comment by GrimmLiberty** [comment]
Ok, so I got home from work, sorry for the delay, 
Cleared it out, made a new profile, 
I went to Online in r2modman and Download, it installed without a dll. 
when I went to the thunderstore page and used "Install with modman", no dll.
 
HOWEVER, then I manually downloaded it from the tunderstore page, and went to settings, All, Import local mod, ... it installed fine. Left me scratching my head... decided to try to verify all steps... 
I then uninstalled it and tried via install with mod manager. and it worked fine. 
  
The only thing I can think happened is bad caching in r2modman????  
But this can be closed.  

Now I can keep using the mod, woohoo! Thank you for your good work and your patience. Looking at it from your side, I see you did what you needed to verify it must be on my end, I truly appreciate that. 

-Grimm

**Comment by SpikeHimself** [comment]
> The only thing I can think happened is bad caching in r2modman????

It must be something along those lines, yeah. Still very strange that the DLL randomly went missing in the first place.. Really weird issue!

Glad you got it sorted!
