### ISSUE TITLE
Can you add a Default connection?

### ISSUE THREAD

**Issue by GoofyWarriorGuy** [SpikeHimself/XPortal#42]
Any way to set a specific Portal as your 'Default' connection, so that if you place a new Portal it Auto connects to the 'Default' Portal without needing to be selected or named?

**Comment by SpikeHimself** [comment]
I think this should be doable, but I'm struggling to think of a method of how to achieve this. Do you have something in mind, in terms of how that would work? In other words: how would you determine which portal is the default?

**Comment by GoofyWarriorGuy** [comment]
Well I don't know the logistics of what is possible or not. Can you have a check box when you are naming a Portal that says 'Default' and if you check that box on a portal it becomes the Default all new portals connect to when they are created? Although maybe this causes a problem if you try to check the 'default' checkbox on a new portal because you can't have it auto uncheck that box on the first portal?

Maybe you'd need to make it pick the first portal Alphabetically on the list to Auto connect to. So whichever Portal you want to make Default you put a 1 in front of the name to make it be the first one the list of portals. Then all new portals will Auto Connect to that first portal on the list until manually changed.

**Comment by SpikeHimself** [comment]
How about a checkbox on the configuration window? Would that work for what you want to achieve? My worry is just that anyone you're playing with could go to another portal and change it.

**Comment by templar4522** [comment]
I wouldn't worry about it too much, other players can also change portal names or directly dismantle portals too. The default most likely will be the home portal anyway.

An alternative would be to save the default for each player. Keep the checkbox there, maybe call it "Your default portal" to emphasize that it's the player's default and not everybody's.

**Comment by SpikeHimself** [comment]
I have to think about this. I think adding a checkbox on the portal config window might be confusing if that setting only applies to the player.

In theory I think it's all possible, I'm just trying to think of a feasible way to present this graphically.

**Comment by GoofyWarriorGuy** [comment]
If it's too complicated to have a specific Portal chosen as a Default, perhaps you could let it work like vanilla portals where if you leave a Portal unnamed (a blank name) then a newly placed portal will auto connect to that unnamed Portal since it too has a blank name when newly placed.

So you could code XPortal to auto connect all newly placed portals to the first (in case there are more than one) 'unnamed' portal on the list.

Either that or you could perhaps pick a name like 'Home'. Then code it so that all new portals auto connect to the first portal on the list named 'Home'.

**Comment by Quentin-ctrL** [comment]
The idea is great.
I prefix my main portal '00_something' to be first in the list.

A checkbox to set the portal as default seems a good idea. (maybe mention the actual default connection)

**Comment by GoofyWarriorGuy** [comment]
Did you give up on Implementing this?

**Comment by SpikeHimself** [comment]
Hi @GoofyWarriorGuy, no, I just haven't had a lot of time due to life events. I'm hoping to pick things up again very soon.

**Comment by SpikeHimself** [comment]
Does this line up with your expectations?

![image](https://github.com/SpikeHimself/XPortal/assets/123466188/82beec1d-0471-496b-ba58-71407bb0e333)

 - The checkbox can only be turned on. Once saved (after pressing OK), it can't be turned off.
 - Turning on the checkbox on another portal does of course unset it on the previous.
 - The default portal is saved in your config file (client-side). Drawback is that it will change if you play on a different server and set a different default portal there.
 - Because of a caveat where portal ZDOIDs can change between sessions, I've decided to use the Portal's location as the identifier for this configuration option. Rounding errors could occur and might break this functionality. I can fix that in a later update if necessary. Using the portal's name was also not an option because there's no restriction on the uniqueness of portal names.
 - You can change the configuration value in the file if you wish, but this is not recommended as it will just unset the default portal in the game.

**Comment by SpikeHimself** [comment]
> The checkbox can only be turned on. Once saved (after pressing OK), it can't be turned off.

Whatever my reasoning for this was at the time, I changed my mind about it. This makes no sense with how the value is stored.

**Comment by SpikeHimself** [comment]
@GoofyWarriorGuy v1.2.16 just went live and includes your feature, thank you for your support!
