### ISSUE TITLE
Compatibility with TargetPortal

### ISSUE THREAD

**Issue by awdwyn** [SpikeHimself/XPortal#46]
I would love to see an enhancement when combining TargetPortal (https://github.com/blaxxun-boop/TargetPortal/) with XPortal

Currently, with both installed, it is possible to configure the portal details (portal name and target) including the longer portal names (which is awesome) however when walking through the portal the map pops up and lets you select a target to warp to. I would love to see this changed so that TargetPortal only opens the map if XPortal doesn't have a destination configured. This would allow a player to set a destination and travel without the map if desired, but also use the amazing features of TargetPortal too.

I've put a matching request in TargetPortals issues, link is here: https://github.com/blaxxun-boop/TargetPortal/issues/24

**Comment by SpikeHimself** [comment]
I was honestly under the impression that XPortal and TargetPortal were mutually exclusive (never tested it though). They both have the same goal but approach it in different ways.

Either way, it sounds specifically as if you want TargetPortal to behave differently. That's not something XPortal can influence.

I'll keep this issue open because I am not unwilling to work on compatiblity if any changes are required in XPortal. Let me know what happens on the other end ;)

**Comment by awdwyn** [comment]
Ok thank you. I suspect TargetPortal would need to be able to check if XPortal has assigned a destination, then either continue to open the map or fallback to XPortals handling. I'll wait to see what blaxxun comes back with (if she's willing to consider this). 

Thanks!

**Comment by SpikeHimself** [comment]
Just as an FYI, XPortal does nothing magical/custom to set the portal destination. It does it in the same way that the vanilla game would (by setting the `target` property of the portal's ZDO).

**Comment by SpikeHimself** [comment]
Hi @awdwyn did you find a solution? Again I don't think XPortal can be of any help here, so I'm closing the issue. If you do need my help with anything regarding this, please do feel free to reopen this issue!
