### ISSUE TITLE
Portals disappear

### ISSUE THREAD

**Issue by Hoogie1980** [SpikeHimself/XPortal#7]
Love this mod.  Small concern though, when I join my dedicated server the portal locations are all gone.  I have to run to each portal to activate it again.  Any help would be appreciated.  Thanks

**Comment by shupershuff** [comment]
Also having this issue. It seemingly randomly allocated 2 portals to show in the dropdown. Sometimes a 3rd and 4th will show available.

**Comment by SpikeHimself** [comment]
Thanks for the reports guys! 

In the latest release I had fixed a bug where portals are duplicated. Or so I thought, because in doing so, this new bug has creeped in. I am working on the solution.

**Comment by BooMaLiCiOuS** [comment]
I have what seems to be the same issue now. I have just installed Xportal yesterday and have had the portals all reset back to no name and no locations to select (two times). This is the only mod I have installed on the server above Valheim Plus.

**Comment by SpikeHimself** [comment]
Hi @BooMaLiCiOuS, thanks for reporting? 

Could you please create a new issue for that? Issue #7 is more than a month old and was caused by code that isn't even in the current version anymore, so it's not the same problem.

When you create a new issue there will be a template to fill out which should give me all the details I need to look into your problem.

Thanks!
