### ISSUE TITLE
XPortal Menu not working

### ISSUE THREAD

**Issue by agmaro** [SpikeHimself/XPortal#82]
Hello! Since the update from today 14/12 the menu for selecting portals from and through is not working. Can't select it, can't close it and obviously can't interact with the portal options.

**Priority**
* High (XPortal does not work at all anymore)

I know with every update the mods tend to break, this is just a heads up so you know that with this update XPortal is not working :)
Thanks a lot!!
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/13674580/LogOutput.log)

**Comment by agmaro** [comment]
Forgot to mention: the portal mechanics work (the player gets teleported), but it's not possible to select the end portal.
thks

**Comment by Vikingtons** [comment]
Can confirm. Here's my console output when interacting with a portal from 0.217.38:
![image](https://github.com/SpikeHimself/XPortal/assets/9853124/897ef115-793f-4e99-baa2-5ef7a6b1540e)
`[Error  : Unity Log] MissingFieldException: Field not found: System.Collections.Generic.Dictionary`2<TMPro.TextMeshProUGUI, string> .Localization.textMeshStrings Due to: Could not find field in class
Stack trace:
XPortal.UI.PortalConfigurationPanel.AddGamepadHint (UnityEngine.GameObject go, System.String buttonName, UnityEngine.KeyCode keyCode) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.UI.PortalConfigurationPanel.InitialiseUI () (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <d85e537a8bc2492eb41ca9fb4a52a72d>:0)
(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)
(wrapper dynamic-method) TeleportWorld.DMD<TeleportWorld::Interact>(TeleportWorld,Humanoid,bool,bool)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <d38f146a96674e468895b47f3870b161>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)`

**Comment by SrMerins55** [comment]
same thing happening to me, can't interact with the portal menu and It blocks everything else, settings included, so I have to alt+f4 out of the game

**Comment by Vikingtons** [comment]
I believe we saw a similar (if not the same) issue with the Hildr's request update way back when

**Comment by Wanderlost2** [comment]
...shoulda built that Portal hub *smh

**Comment by charlouze** [comment]
same for me... unusable portals :'(

**Comment by Vikingtons** [comment]
Working again with latest xportal and jotunn :)

**Comment by SpikeHimself** [comment]
Thanks for reporting everyone. v1.2.20 should have fixed this issue, let me know if you run into any problems.
